name: signin_with_linkedin_example
description: Demonstrates how to use the signin_with_linkedin plugin.
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  signin_with_linkedin:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true